Add reusable ScanList component for displaying previous scans
stephane-segning/lynx-scanner pull request #41
Opened 2024-04-26 12:39 UTC by bryandino673

2024-04-26 13:23 UTC, ValantineSuh approved these changes
Good!

2024-04-27 07:37 UTC, stephane-segning requested changes
Change name to pascal case. E.g `ScanView` => `scan-view`

2024-04-27 07:37 UTC, stephane-segning commented on src/components/ScanViewer.tsx
This component is not part of the ticket

2024-04-27 07:37 UTC, stephane-segning commented on src/components/ScanList.tsx
> +);
Remove this component into another file

2024-04-27 08:57 UTC, Ngha-Boris reviewed
Hello @bryandino673 can you consider adding error handling for cases where the data passed to the components is incomplete or malformed. For example, if avatarGroup or rawData is missing or invalid, you might want to handle these cases gracefully to prevent runtime errors.

2024-04-27 12:47 UTC, stephane-segning requested changes

2024-04-27 12:47 UTC, stephane-segning commented on src/components/ScanViewer.tsx
Remove this component

2024-04-27 12:47 UTC, stephane-segning commented on package.json
Cancel these changes. They're not related to this ticket

2024-04-27 12:47 UTC, stephane-segning commented on .husky/pre-commit
Cancel these changes. They're not related to this ticket

2024-05-02 12:30 UTC, Ngha-Boris approved these changes

2024-05-04 14:05 UTC, stephane-segning requested changes

2024-05-04 14:05 UTC, stephane-segning commented on src/components/ScanViewer.tsx
Remove this component

2024-05-04 17:24 UTC, bryandino673 commented on src/components/ScanViewer.tsx
Understood sir

2024-05-04 21:30 UTC, stephane-segning approved these changes

2024-05-06 08:13 UTC, merged