perf(frontend) : Setup redux toolkit with persist
stephane-segning/lynx-scanner pull request #44
Opened 2024-05-02 13:09 UTC by Arielpetit

Please review this PR @stephane-segning @ValantineSuh @Ngha-Boris

2024-05-02 14:24 UTC, ValantineSuh approved these changes
Good!

2024-05-02 14:43 UTC, Ngha-Boris requested changes

2024-05-02 14:43 UTC, Ngha-Boris commented on src/app.tsx
> +        </div>
The LoginButton and LogoutButton are rendered outside of routes in app.tsx. This means they'll be visible on all pages.
Please @Arielpetit, consider conditionally rendering the buttons based on the isLoggedIn state.

2024-05-02 20:00 UTC, stephane-segning requested changes
You integrated redux, not redux toolkit. Please read it again [here](https://redux-toolkit.js.org/introduction/getting-started) and [here](https://redux-toolkit.js.org/usage/usage-with-typescript). Read first before the single implementation please.

2024-05-06 10:34 UTC, Arielpetit commented on package.json
> +    "@types/redux-persist": "^4.3.1",
Done!!!

2024-05-06 10:35 UTC, Arielpetit commented on src/components/LoginButton.tsx
Done

2024-05-06 10:35 UTC, Arielpetit commented on src/store/actions.ts
Done

2024-05-06 10:35 UTC, Arielpetit commented on src/store/reducers.ts
Done

2024-05-06 10:35 UTC, Arielpetit commented
Hey please @stephane-segning and @Ngha-Boris review this again

2024-05-06 11:20 UTC, Ngha-Boris commented on .husky/pre-commit
Hello @Arielpetit what is this file for

2024-05-07 10:27 UTC, stephane-segning requested changes
Very good improvement. Now, address these points please

2024-05-07 10:27 UTC, stephane-segning commented on package.json
> +    "@reduxjs/toolkit": "^2.2.3",
This should be in dep, not dev dep

2024-05-07 10:27 UTC, stephane-segning commented on src/components/home-page.tsx
Cancel all these changes

2024-05-07 10:43 UTC, Arielpetit commented on src/components/home-page.tsx
Done

2024-05-07 10:43 UTC, Arielpetit commented on package.json
> +    "@reduxjs/toolkit": "^2.2.3",
DOne

2024-05-07 10:48 UTC, stephane-segning requested changes

2024-05-07 10:48 UTC, stephane-segning commented on .husky/pre-commit
Cancel this change

2024-05-13 07:51 UTC, ValantineSuh commented on .husky/pre-commit
Kindly cancel the change requested by Sir Stephane.

2024-07-22 09:05 UTC, closed without merging