feat(frontend): integrated sentry with the react application
stephane-segning/lynx-scanner pull request #49
Opened 2024-05-10 07:36 UTC by mbunwe-victor

Integrating sentry with react application in the frontend.

2024-05-10 07:42 UTC, Ngha-Boris requested changes
Hello @mbunwe-victor one check is failing please consider checking that.

2024-05-10 09:20 UTC, Ngha-Boris approved these changes

2024-05-10 09:20 UTC, mbunwe-victor commented
> Hello @mbunwe-victor one check is failing please consider checking that.

Done

2024-05-10 09:21 UTC, Ngha-Boris approved these changes
LGTM

2024-07-22 08:38 UTC, stephane-segning approved these changes

2024-07-22 09:04 UTC, merged